<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>firstLineMatch</key>
	<string>-* beginning of /dev/log/.*</string>
	<key>name</key>
	<string>logcat (-v threadtime)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#verbose</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#debug</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#info</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#warn</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#error</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>debug</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.line</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.logcat.timestamp.date</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.logcat.timestamp.time</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.pid</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.tid</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.logcat.type</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.logcat.tag</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.logcat.msg</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)^ (?:\s*(\d+:)\s*)? ([\d-]+)\s+([\d:.]+)\s+ (\d+)[-\s]+(\d+)\S*\s+ ([D])[/\s]+(.*?):\s+ (.*) $</string>
					<key>name</key>
					<string>meta.logcat.line.debug</string>
				</dict>
			</array>
		</dict>
		<key>error</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.line</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.logcat.timestamp.date</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.logcat.timestamp.time</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.pid</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.tid</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.logcat.type</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.logcat.tag</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.logcat.msg</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)^ (?:\s*(\d+:)\s*)? ([\d-]+)\s+([\d:.]+)\s+ (\d+)[-\s]+(\d+)\S*\s+ ([EF])[/\s]+(.*?):\s+ (.*) $</string>
					<key>name</key>
					<string>meta.logcat.line.error</string>
				</dict>
			</array>
		</dict>
		<key>info</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.line</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.logcat.timestamp.date</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.logcat.timestamp.time</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.pid</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.tid</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.logcat.type</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.logcat.tag</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.logcat.msg</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)^ (?:\s*(\d+:)\s*)? ([\d-]+)\s+([\d:.]+)\s+ (\d+)[-\s]+(\d+)\S*\s+ ([I])[/\s]+(.*?):\s+ (.*) $</string>
					<key>name</key>
					<string>meta.logcat.line.info</string>
				</dict>
			</array>
		</dict>
		<key>verbose</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.line</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.logcat.timestamp.date</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.logcat.timestamp.time</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.pid</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.tid</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>comment.logcat.type</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.logcat.tag</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>comment.logcat.msg</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)^ (?:\s*(\d+:)\s*)? ([\d-]+)\s+([\d:.]+)\s+ (\d+)[-\s]+(\d+)\S*\s+ ([V])[/\s]+(.*?):\s+ (.*) $</string>
					<key>name</key>
					<string>meta.logcat.line.verbose</string>
				</dict>
			</array>
		</dict>
		<key>warn</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.line</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.logcat.timestamp.date</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.logcat.timestamp.time</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.pid</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.logcat.tid</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.logcat.type</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.logcat.tag</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>keyword.logcat.msg</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)^ (?:\s*(\d+:)\s*)? ([\d-]+)\s+([\d:.]+)\s+ (\d+)[-\s]+(\d+)\S*\s+ ([W])[/\s]+(.*?):\s+ (.*) $</string>
					<key>name</key>
					<string>meta.logcat.line.warn</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.logcat.threadtime</string>
	<key>uuid</key>
	<string>fbfb3802-6282-490b-8dea-14b7dcbe7469</string>
</dict>
</plist>
